# Generated by Django 4.1 on 2022-08-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('availability', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
