# Generated by Django 4.1 on 2022-08-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
